homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 52.2750
  longitude: 8.0667
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 98
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin
  # Customize
  customize: !include customize.yaml

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
  base_url: berichta.duckdns.org
#  ssl_certificate: /ssl/fullchain.pem
#  ssl_key: /ssl/privkey.pem

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
# discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# HassIO
hassio:

# Track the sun
sun:
  
# iOS
ios:
  
# ifttt
ifttt:
  key: !secret ifttt
  
# Notify
notify:
  - name: gmail
    platform: smtp
    server: smtp.gmail.com
    port: 587
    timeout: 15
    sender: paul.nb@gmail.com
    starttls: true
    username: paul.nb@gmail.com
    password: !secret gmail
    recipient: paul.nb@gmail.com

# Text to speech
tts:
  - platform: google
    language: 'de'

sensor: !include sensors.yaml
group: !include groups.yaml
automation: !include automations.yaml
device_tracker: !include device_tracker.yaml
zone: !include zones.yaml
script: !include_dir_named scripts
switch: !include switches.yaml

input_slider: 
  volume_radio:
    name: Lautstärke
    icon: mdi:volume-high
    min: 0
    max: 1
    initial: 0.5
    step: 0.1
    
input_select:
  radio_station:
    name: 'Radiosender:'
    options:
     - "EgoFM Riff"
     - "StarFM Classics"
     
# Media Player
media_player:
  - platform: cast
    host: 192.168.178.65
  - platform: cast
    host: 192.168.178.26
  - platform: firetv
    device: firetv
  - platform: samsungtv
    host: 192.168.178.22
    name: Fernseher