####################################################
#                                                  #
# FRITZ BOX                                        #
#                                                  #
####################################################

- platform: fritz
  track_new_devices: yes
  consider_home: 180