####################################################
#                                                  #
# SENSORS                                          #
#                                                  #
####################################################

####################################################
#                                                  #
# WETTER                                           #
#                                                  #
####################################################

- platform: yr
  monitored_conditions:
    - temperature
    - cloudiness
    - symbol
    - windSpeed
    
# - platform: openweathermap
#  api_key: !secret owm_key
#  forecast: 1
#  language: de
#  monitored_conditions:
#  - weather
#  - temperature
#  - wind_speed
#  - wind_bearing
#  - humidity
#  - pressure
#  - clouds
#  - rain
#  - snow
    
####################################################
#                                                  #
# HA SERVER METRICS                                #
#                                                  #
####################################################

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_use_percent
    - type: processor_use
#    - type: since_last_boot
    
####################################################
#                                                  #
#  FRITZBOX
#                                                  #
####################################################

#- platform: fritzbox_callmonitor
#  name: Festnetz
#  username: hassio
#  password: !secret fritzbock_callmonitor
#  phonebook: 0
#  prefixes:
#  - '+49'
#  - '+49541'
#  - '0541'
- platform: fritzbox_netmonitor
    
####################################################
#                                                  #
#  TEMPLATES                                       #
#                                                  #
####################################################

- platform: template
  sensors:
    firetv:
      entity_id: device_tracker.firetv
      value_template: '{% if is_state("device_tracker.firetv", "home") %}Online{% else %}Offline{% endif %}'
      friendly_name: 'FireTV'
    playstation:
      entity_id: device_tracker.ps4931345
      value_template: '{% if is_state("device_tracker.ps4931345", "home") %}Online{% else %}Offline{% endif %}'
      friendly_name: 'PlayStation4'
    tv55c8700:
      entity_id: device_tracker.tv55c8700
      value_template: '{% if is_state("device_tracker.tv55c8700", "home") %}Online{% else %}Offline{% endif %}'
      friendly_name: 'Fernseher'
    diskstation:
      entity_id: device_tracker.diskstation
      value_template: '{% if is_state("device_tracker.diskstation", "home") %}Online{% else %}Offline{% endif %}'
      friendly_name: 'DiskStation'
    chromecastultra:
      entity_id: device_tracker.chromecastultra
      value_template: '{% if is_state("device_tracker.chromecastultra", "home") %}Online{% else %}Offline{% endif %}'
      friendly_name: 'ChromeCast'
    paulsmbp:
      entity_id: device_tracker.paulsmbp
      value_template: '{% if is_state("device_tracker.paulsmbp", "home") %}Online{% else %}Offline{% endif %}'
      friendly_name: 'MacBook Pro'
    googlehome:
      entity_id: device_tracker.googlehome
      value_template: '{% if is_state("device_tracker.googlehome", "home") %}Online{% else %}Offline{% endif %}'
      friendly_name: 'Google Home'
      
####################################################
#
# FRITZ!BOX
#
####################################################

    sensor_fritz_netmonitor:
      value_template: '{% if is_state("sensor.fritz_netmonitor", "online") %}Online{% else %}Offline{% endif %}'
      friendly_name: Internet
    fritzbox_external_ip:
      value_template: '{{ states.sensor.fritz_netmonitor.attributes.external_ip }}'
    fritzbox_max_byte_rate_up:
      value_template: >-
        {%- if states.sensor.fritz_netmonitor.attributes.max_byte_rate_up %}
            {{ states.sensor.fritz_netmonitor.attributes.max_byte_rate_up | filesizeformat }}
        {% else %}
            {{ sensor.fritzbox_max_byte_rate_up | filesizeformat }}
        {%- endif %}
    fritzbox_max_byte_rate_down:
      value_template: >-
        {%- if states.sensor.fritz_netmonitor.attributes.max_byte_rate_down %}
            {{ states.sensor.fritz_netmonitor.attributes.max_byte_rate_down | filesizeformat }}
        {% else %}
            {{ sensor.fritzbox_max_byte_rate_down | filesizeformat }}
        {%- endif %}

####################################################
#
# SYNOLOGY
#
####################################################

- platform: synologydsm
  host: 192.168.178.100
  username: HASS
  password: !secret synologydsm
  monitored_conditions:
    - cpu_total_load
    - memory_real_usage
    - disk_name
    - disk_smart_status
    - disk_status
    - volume_status
    - volume_size_total
    - volume_size_used
    - volume_percentage_used
#     - volume_disk_temp_avg
    
####################################################
#
# GOOGLE DISTANCE
#
####################################################

# - platform: google_travel_time
#   api_key: !secret google_api#
#   origin: Kölner Straße 3a, Osnabrück, Germany
#   destination: Niedersachsenstraße 6, 49186 Bad Iburg, Germany